# Generated by Django 6.0.6 on 2026-06-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milansetu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='partner_age_max',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='partner_age_min',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='partner_height_max_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='partner_height_min_cm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='partner_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='partner_religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
