# Generated by Django 6.0.6 on 2026-06-23 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_partner_prefs_to_ideal_partner(apps, schema_editor):
    ProfileDetails = apps.get_model("milansetu", "ProfileDetails")
    IdealPartner = apps.get_model("milansetu", "IdealPartner")

    for profile in ProfileDetails.objects.filter(user__isnull=False).select_related("user"):
        IdealPartner.objects.update_or_create(
            user_id=profile.user_id,
            defaults={
                "age_min": profile.partner_age_min,
                "age_max": profile.partner_age_max,
                "height_min_cm": profile.partner_height_min_cm,
                "height_max_cm": profile.partner_height_max_cm,
                "religion": profile.partner_religion,
                "location": profile.partner_location,
            },
        )


def create_ideal_partner_for_remaining_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    IdealPartner = apps.get_model("milansetu", "IdealPartner")
    for user_id in User.objects.values_list("id", flat=True):
        IdealPartner.objects.get_or_create(user_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ("milansetu", "0002_profiledetails_partner_age_max_and_more"),
        ("users", "0003_user_membership_tier_user_premium_expires_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IdealPartner",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("age_min", models.IntegerField(blank=True, null=True)),
                ("age_max", models.IntegerField(blank=True, null=True)),
                ("height_min_cm", models.IntegerField(blank=True, null=True)),
                ("height_max_cm", models.IntegerField(blank=True, null=True)),
                ("religion", models.CharField(blank=True, max_length=100, null=True)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("mother_tongue", models.CharField(blank=True, max_length=100, null=True)),
                ("marital_status", models.CharField(blank=True, max_length=100, null=True)),
                ("education", models.CharField(blank=True, max_length=255, null=True)),
                ("industry", models.CharField(blank=True, max_length=255, null=True)),
                ("min_income", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("max_income", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("income_unit", models.CharField(blank=True, max_length=20, null=True)),
                ("manglik_status", models.CharField(blank=True, max_length=50, null=True)),
                ("family_values", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ideal_partner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ideal_partner",
            },
        ),
        migrations.RunPython(migrate_partner_prefs_to_ideal_partner, migrations.RunPython.noop),
        migrations.RunPython(create_ideal_partner_for_remaining_users, migrations.RunPython.noop),
        migrations.RemoveField(model_name="profiledetails", name="partner_age_max"),
        migrations.RemoveField(model_name="profiledetails", name="partner_age_min"),
        migrations.RemoveField(model_name="profiledetails", name="partner_height_max_cm"),
        migrations.RemoveField(model_name="profiledetails", name="partner_height_min_cm"),
        migrations.RemoveField(model_name="profiledetails", name="partner_location"),
        migrations.RemoveField(model_name="profiledetails", name="partner_religion"),
        migrations.CreateModel(
            name="SentInterest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("message", models.TextField(blank=True, null=True)),
                ("response_message", models.TextField(blank=True, null=True)),
                ("match_score", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "receiver_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_interests",
                        to="milansetu.profiledetails",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sent_interests",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("sender", "receiver_profile"),
                        name="unique_interest_per_sender_receiver",
                    )
                ],
            },
        ),
    ]
