# Generated by Django 6.0.6 on 2026-06-23 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milansetu', '0003_remove_profiledetails_partner_age_max_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_data', models.BinaryField()),
                ('content_type', models.CharField(default='image/jpeg', max_length=100)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('sensitivity_status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending Review')], default='pending', max_length=20)),
                ('sensitivity_score', models.PositiveSmallIntegerField(default=0)),
                ('sensitivity_message', models.CharField(blank=True, default='', max_length=500)),
                ('is_profile_photo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_gallery',
                'ordering': ['-is_profile_photo', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='profile_photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_for', to='milansetu.usergallery'),
        ),
    ]
